version: '3'
services:
  front:
    image: node
    # environment:
      # - NODE_ENV=production
    tty: true
    working_dir: /front
    volumes:
      - ./front/:/front
    restart: always
    # ports:
    #   - "3000:3000"
    command: "bash"
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes: 
      # - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # sslの鍵 (nginx.confを参照)
      - ./nginx/key_cert:/key_cert
  api:
    image: node
    # environment:
      # - NODE_ENV=production
    tty: true
    working_dir: /api
    volumes:
      - ./api/:/api
    restart: always
    # ports:
      # - "3001:3001"
    command: "bash"
  neo4j:
    image: neo4j
    restart: always
    ports: 
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes: 
      - ./volumes/neo4j/data:/data
      - ./volumes/neo4j/logs:/logs
      - ./volumes/neo4j/import:/import
      - ./neo4j/plugins:/plugins
      # - ./neo4j/conf:/conf
    environment: 
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_dbms_connector_http_advertised__address=:7474
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/blz